EXCHANGE_AS = "as"
EXCHANGE_EM = "em"
EXCHANGE_THS = "ths"
EXCHANGE_BINANCE = "binance"
EXCHANGE_ASINDEX = "asindex"

EXCHANGE_OPTIONS = [EXCHANGE_AS, EXCHANGE_EM, EXCHANGE_THS, EXCHANGE_BINANCE]

# K 线页（Flight tag 前缀）：与全局 EXCHANGE_OPTIONS 不同，含指数 asindex、无 em/binance
KLINE_EXCHANGE_OPTIONS = (EXCHANGE_AS, EXCHANGE_THS, EXCHANGE_ASINDEX)

KLINE_DEFAULT_FREQ = "1d"
KLINE_FREQ_OPTIONS = ("1d", "1h", "30m", "15m", "5m", "1w")
KLINE_FREQ_SET = frozenset(KLINE_FREQ_OPTIONS)
